-- 清空表的:  --
DROP TABLE `nnld_access`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_address`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_benqi`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_bonus`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_card`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_cash`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_change_tree`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_chongzhi`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_cody`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_cptype`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_fahuo`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_fck`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_fck2`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_fee`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_fehlist`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_fenhong`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_form`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_form_class`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_fuwu`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_gouwu`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_history`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_img`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_jifen`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_msg`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_news_a`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_news_class`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_peng`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_plan`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_product`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_promo`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_remit`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_shangpin`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_shouru`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_times`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_tiqu`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_uplevel`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_xiaoshou`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_yeji`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_yj`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `nnld_zhuanj`;
-- <fen> --
