-- 表的数据: nnld_cody --
INSERT INTO `nnld_cody` VALUES ('1','profile');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('2','password');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('3','Jj_FA');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('4','4');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('5','5');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('6','6');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('7','7');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('8','8');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('9','9');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('10','10');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('11','11');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('12','12');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('13','13');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('14','14');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('15','15');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('16','16');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('17','17');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('18','18');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('19','19');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('20','20');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('21','21');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('22','22');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('23','23');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('24','24');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('25','25');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('26','26');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('27','27');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('28','28');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('29','29');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('30','30');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('31','31');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('32','32');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('33','33');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('34','34');-- <fen> --
INSERT INTO `nnld_cody` VALUES ('35','35');-- <fen> --
