-- 表的数据: nnld_access --
INSERT INTO `nnld_access` VALUES ('2','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','40','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','30','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','69','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','50','3','40','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','50','3','40','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','50','3','40','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','7','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','39','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','39','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','49','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','2','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','3','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','4','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','5','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','6','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','7','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','11','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('5','25','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('5','51','2','25','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','39','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','69','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','30','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','40','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','49','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','69','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','30','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','40','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','37','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','36','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','35','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','34','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','33','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','32','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','31','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','32','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','31','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','69','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','30','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','40','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','50','3','40','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','39','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','49','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','84','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','85','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','84','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','85','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','84','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','85','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','7','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','6','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','2','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','83','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','7','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','6','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','2','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','83','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','37','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','36','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','35','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','34','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','33','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','32','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','31','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','40','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','30','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','69','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','50','3','40','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','50','3','40','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','50','3','40','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','7','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','39','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','39','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','49','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','2','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','3','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','4','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','5','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','6','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','7','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','11','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('5','25','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('5','51','2','25','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','39','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','69','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','30','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','40','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','49','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','69','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','30','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','40','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','37','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','36','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','35','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','34','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','33','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','32','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','31','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','32','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','31','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','69','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','30','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','40','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','50','3','40','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','39','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','49','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','84','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','85','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','84','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','85','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','84','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','85','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','7','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','6','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','2','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','83','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','7','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','6','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','2','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','83','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','37','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','36','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','35','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','34','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','33','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','32','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','31','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','40','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','30','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','69','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','50','3','40','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','50','3','40','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','50','3','40','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','7','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','39','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','39','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','49','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','2','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','3','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','4','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','5','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','6','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','7','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','11','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('5','25','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('5','51','2','25','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','39','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','69','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','30','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','40','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','49','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','69','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','30','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','40','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','37','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','36','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','35','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','34','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','33','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','32','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','31','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','32','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','31','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','69','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','30','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','40','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','50','3','40','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','39','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','49','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','84','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','85','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','84','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','85','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','84','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','85','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','7','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','6','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','2','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','83','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','7','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','6','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','2','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','83','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','37','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','36','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','35','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','34','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','33','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','32','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','31','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','40','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','30','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','69','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','50','3','40','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','50','3','40','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','50','3','40','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','7','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','39','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','39','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','49','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','2','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','3','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','4','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','5','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','6','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','7','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('4','11','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('5','25','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('5','51','2','25','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','39','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','69','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','30','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','40','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','49','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','69','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','30','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('3','40','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','37','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','36','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','35','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','34','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','33','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','32','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','31','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','32','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','31','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','1','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','69','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','30','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','40','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','50','3','40','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','39','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','49','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','84','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','85','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','84','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('2','85','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','84','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','85','1','0','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','7','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','6','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','2','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('1','83','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','7','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','6','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','2','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','83','2','1','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','37','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','36','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','35','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','34','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','33','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','32','3','30','');-- <fen> --
INSERT INTO `nnld_access` VALUES ('7','31','3','30','');-- <fen> --
